var today = new Date()
var x = today.getHours()
console.log(x)
var x = today.getMinutes()
console.log(x)
var x = today.getSeconds()
console.log(x)
var x = today.getDate()
console.log(x)
var x = today.getMonth()
console.log(x)